version: "3.6"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: hashtag-watch-server
    ports:
      - "6767:6767"
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./esdata/db:/usr/share/elasticsearch/data
